version: '3'

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    env_file:
      - .env
    container_name: app--wb-service
    ports:
      - "8000:8000"
    volumes:
      - '.:/opt/app'
    restart: always

#  parser:
#    build:
#      context: .
#      args:
#        ENVIRONMENT: ${ENVIRONMENT:-development}
#    env_file:
#      - .env
#    container_name: parse--wb-mfd
#    command: ["make", "parse"]
#    volumes:
#      - '.:/opt/app'
#    restart: always